import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";

const lato = Lato({
  variable: "--font-lato-sans",
  subsets: ["latin"],
  weight: "100",
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${lato.variable} ${geistSans.variable} ${geistMono.variable} antialiased px-20`}
        className={`${lato.variable}`}
      >
        <Hero />
        <div className="m-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
