import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full container min-h-screen flex items-center flex-col relative ${inter.className}`}
      >
        <Provider>
          <Navbar />
          <main className="pt-4">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
