import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen max-w-4xl mx-auto p-4 sm:p-8 lg:p-16">
      <div className="space-y-8 animate-fade-in">{children}</div>
    </div>
  );
}
